export const formLogin = {
    user: "user",
    password: "password"
}

export const formAllDataUser = {
    id: "_id",
    name: "firstName",
    lastName: "lastName",
    email: "email",
    username: "user",
    password: "password",
    gender: "gender",
    birthDate: "birthDate",
    description: "description",
    photo: "file",
    link: "photo", 
    city: "cityBirth",
    career: "degree",
    socialMedia: "socialMediaHandles",
    availableHours: "businessHours",
    phone: "phoneNumber",
    tipo: "type",
}

export const formAllListings = {
    idlisting: '_id',
    titulo: "title",
    direccion: "address",
    complemento: "address2",
    barrio: "neighborhood",
    latitud: "latitude",
    longitud: "longitude",
    tiempo: "timeToUN",
    precio: "price",
    descripcion: "description",
    iduser: "landlord",
    compartido: "shared",
    fotos: "files",
    fechaPublicacion: "date",
    caracteristicas: "characteristics",
    amoblado: "furnished",
    estrato: "stratum",
    areaPrivada: "privateArea",
    habitaciones: "rooms",
    banoPrivado: "privateBathrooms",
    mascotas: "petFriendly",
    parqueadero: "carParking",
    bicicletero: "bicycleParking",
    almacen: "storage",
    areasComunitarias: "communalAreas",
    tipo: "type",
    apartaestudio: "StudioApartment",
    apartamento: "Apartment",
    habitacion: "Room",
    imagenes: "photos",
    valoracion: "rating",
    activo: "active",
    valoradoEstudiantes: "reviewedByTenants",
    areaLimpieza: "cleaningArea",
    numeroBanos: "privateBathrooms",
    cocina: "kitchen",
}